### PR TITLE
Use editor debug component instead of duplicated code (see GN-3152)

### PR DESCRIPTION
**Pull request by benjay10**
This plugin now uses the debug component from the ember-rdfa-editor instead of duplicating code. As of now this depends on release 0.50.0-beta.6 of the editor.
Was tested, but please, test the build and its dependencies as a double check.

### CODE REVIEW

**Review by nvdk — CHANGES_REQUESTED** [review]
this at least seems to break the plugin (it doesn't show up anymore)

**Comment by abeforgit** [comment]
Not sure what's going on, I've had a look and didn't see anything immediately wrong.
I've also tried #4 with the latest beta and it works. Then I've tried to merge that pr into this one and then it didnt work anymore. Id suggest having a close look at the html tree before and after, the plugin may have had more rdfa before which is now lost due to replacing the template

**Comment by abeforgit** [comment]
For debugging, you can use the global `__EDITOR` in the js console, that's a controller instance. You have access to the [Datastore](https://github.com/lblod/ember-rdfa-editor/wiki/Datastore) there so you can see what the editor knows about the document's rdfa

**Comment by lagartoverde** [comment]
I defined the prefix ext and it works now, ext should be in the editor defaults so something to look in the editor, but we can merge this branch now

**Review by lagartoverde — APPROVED** [review]

**Pull request merged**
